csv:
  filename: images.txt
  has_header: no

docker:
  username: robot$mosiphubid+mosiphubid-bot
  token: zPZN0PdUeISMKKtA79nhPkqALfeA0tPu
  destination_organization: mosiphubid
  registry_url: 10.0.3.128:8080
  imageExitUrl: https://registry.hub.docker.com/v2/
process:
  count: 3
